### ISSUE TITLE
Length of 'targets' key in dataset

### ISSUE THREAD

**Issue by ashishm-io** [carla-simulator/imitation-learning#13]
The [README ](https://github.com/carla-simulator/imitation-learning/blob/master/README.md)mentions that in the provided dataset, the 'targets' key has 27 measurements. 
But when I printed out the size of 'targerts' it showed that it has 28 measurements .

Here is the code: 
``` python
datasetDirTrain = '/mnt/AshishMehta/Downloads/CARLAImitationLearningDataset/AgentHuman/SeqTrain/'
datasetDirVal = '/mnt/AshishMehta/Downloads/CARLAImitationLearningDataset/AgentHuman/SeqVal/'

import glob
import h5py
datasetFilesTrain = glob.glob(datasetDirTrain+'*.h5')
datasetFilesVal = glob.glob(datasetDirVal+'*.h5')

dataset = h5py.File(datasetFilesTrain[120], 'r')

print(list(dataset.keys()))
print(dataset['rgb'].shape)
print(dataset['targets'].shape)

ind = 120

print(dataset['targets'][ind])
dataset.close()
```
The output is as follows :

> ['depth', 'labels', 'rgb', 'targets']
(200, 88, 200, 3)
(200, 28)
[-2.0544434e-01  6.4567566e-01  0.0000000e+00  0.0000000e+00
  0.0000000e+00 -1.9859870e-01  6.4567566e-01  0.0000000e+00
 -3.1488324e+02  1.5389464e+04  2.5427959e+01  9.4275820e+06
  2.1926109e+05  2.3462818e+06  0.0000000e+00  6.0470324e-02
  1.1559283e+01  1.5627192e+00 -4.1669765e+00  8.0673536e+07
  6.6544400e+05 -3.6079049e-02  9.9933618e-01  5.0120126e-03
  2.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]

**Comment by felipecode** [comment]
Hello,
I just rechecked the dataset.
You are right! There is indeed another parameter, the yaw angle for the camera. 
But it is not used for this dataset since all cameras are central ( Yaw = 0)

Thanks a lot for the comment.

Regards

**Comment by ashishm-io** [comment]
Thanks for your reply.
