### ISSUE TITLE
About the shape of dataset "target"

### ISSUE THREAD

**Issue by lvlvlvlvlv** [carla-simulator/imitation-learning#15]
@felipecode 
Hi there,
I have checked the .h5 dataset and found that the shape of "target" part is 200 * 28.
I know the meaning of the num of cols "28". But I don't know the meaning of the rows number "200". Why are there 200 points for every image? what does it represent？ 

Look forward to your reply~  Thanks a lot in advance!

**Comment by felipecode** [comment]
Hello @lvlvlvlvlv 
We have 200 images / targets per HDF5 file.
It was just the way I divided the data in order to avoid having too large files.

**Comment by lvlvlvlvlv** [comment]
OK. I got it. Thanks very much~ @felipecode
