### ISSUE TITLE
run_CIL not working with Carla 0.8.2

### ISSUE THREAD

**Issue by Florence-C** [carla-simulator/imitation-learning#33]
Hello, 

I am facing a problem when I launch the imitation learning with the new version of Carla, it seems not to work. 
The error I get is the following : 

`Traceback (most recent call last):`
 `File "run_CIL.py", line 72, in <module> `
 `   args.host, args.port)`
`  File "/home/florence/tensorflow1.5-3.5/lib/python3.5/site-packages/carla/driving_benchmark/driving_benchmark.py", line 294, in run_driving_benchmark `
   ` benchmark_summary = benchmark.benchmark_agent(experiment_suite, agent, client)  ` 
`  File "/home/florence/tensorflow1.5-3.5/lib/python3.5/site-packages/carla/driving_benchmark/driving_benchmark.py", line 129, in benchmark_agent `
 `   + '.' + str(end_index)) `
 `File "/home/florence/tensorflow1.5-3.5/lib/python3.5/site-packages/carla/driving_benchmark/driving_benchmark.py", line 206, in _run_navigation_episode `
 `   measurements, sensor_data = client.read_data() `
`  File "/home/florence/tensorflow1.5-3.5/lib/python3.5/site-packages/carla/client.py", line 127, in read_data `
 `   return pb_message, dict(x for x in self._read_sensor_data())`
`  File "/home/florence/tensorflow1.5-3.5/lib/python3.5/site-packages/carla/client.py", line 127, in <genexpr> `
`    return pb_message, dict(x for x in self._read_sensor_data()) `
`  File "/home/florence/tensorflow1.5-3.5/lib/python3.5/site-packages/carla/client.py", line 175, in _read_sensor_data `
`    yield self._parse_sensor_data(data) `
`  File "/home/florence/tensorflow1.5-3.5/lib/python3.5/site-packages/carla/client.py", line 180, in _parse_sensor_data `
`    return parser.name, parser.parse_raw_data(data[4:]) `
`  File "/home/florence/tensorflow1.5-3.5/lib/python3.5/site-packages/carla/client.py", line 196, in parse_image `
`    return sensor.Image(frame_number, width, height, image_type, fov, data[24:]) `
`  File "/home/florence/tensorflow1.5-3.5/lib/python3.5/site-packages/carla/sensor.py", line 149, in __init__ `
`    assert len(raw_data) == 4 * width * height `
`AssertionError `

This error is weird as the assertion is the same in the previous version of carla...

Thank you in advance

Florence

**Comment by felipecode** [comment]
In which operating system are you executing ?

**Comment by Florence-C** [comment]
I am on Ubuntu 16.04

**Comment by Florence-C** [comment]
Hello, 

My bad, I think I installed the new Carla version with the wrong version of python. 
I reinstalled it and it works. 

Thanks !

Closing the issue
