### ISSUE TITLE
Mean subtracted images/image preprocessing?

### ISSUE THREAD

**Issue by yanii** [carla-simulator/imitation-learning#35]
Just trying to run a model trained on this dataset with CARLA for benchmarking, and realized that the images in it seems to be mean subtracted, but I can't seem to find the actual mean anywhere in your code, am I missing it? 

Any information you could let me know on the preprocessing of the images would be helpful. Sorry if I've missed it somewhere!

**Comment by felipecode** [comment]
The images from the dataset are not mean subtracted.
Why did you think so ? How are you plotting the images ?

Cheers

**Comment by yanii** [comment]
haha.. you're correct, they were being processed elsewhere in my code :-) Sorry about that, should have looked a bit harder!
