### ISSUE TITLE
Results replecation

### ISSUE THREAD

**Issue by mattangus** [carla-simulator/imitation-learning#43]
Hello,

In the paper you report 88% completion rate. However when I run the trained model from this repo only one of the 25 straight runs pass (4%). When I double the timeout it goes up to 47%. Do you use a custom benchmark to achieve the 88% result reported?

The command used is:

`python3 run_CIL.py --host <ip to remote machine>`

I have a TitanX on the machine that I'm running this on.

**Comment by felipecode** [comment]
Which version of CARLA are you using ?

**Comment by mattangus** [comment]
0.8.2, but the python client is from the branch `CS1_client_side_agents`.

**Comment by felipecode** [comment]
Please try to use with the python client from the 0.8.2 release.

**Comment by mattangus** [comment]
Sorry I should have been more clear. I used the client that came with 0.8.2 for the first run, which got 4%. I then changed it to the branch and double the timeout calculation.

**Comment by felipecode** [comment]
I will try to replicate. Maybe it is some newer tensorflow version issue ?
Try running with tensorflow 1.1

**Comment by felipecode** [comment]
I am sorry.
I have no Idea what is the problem that you have.
I was just able to replicate the straight passes.
What I did.

Downloaded CARLA 0.8.2 release pre compiled version for linux.
Made a conda environment
On that environemnet.
I installed carla from the 0.8.2 package 
Installed tensorflow 1.7 ( It should work with 1.1 as well , i just had a newer cuda installed)
Executed
python run_CIL.py 

It worked !

Another thing I noticed. This repo was made thinking about python2. Maybe it is not python3 friendly for some reason.

**Comment by mattangus** [comment]
Ok, I'll give that a try and let you know!

**Comment by mattangus** [comment]
What command do you use to run Carla?

**Comment by felipecode** [comment]
sh CarlaUE4.sh -windowed -world-port=2000 -ResX=1033 -ResY=750

The ResX and ResY shouldn't affect is just to adjust the server window display

**Comment by felipecode** [comment]
Have you been able to replicate the results in the end ?

**Comment by mattangus** [comment]
Yes, I'm not sure what the problem was but I did replicate! Thanks for the help.
