### ISSUE TITLE
Connection to server problem

### ISSUE THREAD

**Issue by eds89** [carla-simulator/imitation-learning#45]
Hi.
When both server and client are on the same computer, what address should I use to connect to the server (e.g. 'localhost', '127.0.0.1', or the computer's name)? I can confirm the server is set up and running correctly, as identified by TCPview, but the only message returned by the experiment client are 'connection timed out', or 'failed to read from server'). Client and server ports match.

**Comment by eds89** [comment]
Fixed.

**Comment by Rookie-81** [comment]
any idea how you fixed it?
