### ISSUE TITLE
Question about the provided dataset

### ISSUE THREAD

**Issue by AliBaheri** [carla-simulator/imitation-learning#48]
Thanks for sharing the great work.

I have a question abut the dataset. I  understand that each .h5 consists of 200 images, but my question how these .h5 have been collected? Particularly, I mean these files starts from `data_03663.h5` and ends by `data_06951.h5`. Dose all of these files have been collected sequentially? Does it mean these files are part of sequence or episodes?

Thanks for clarification.
Best.

**Comment by AliBaheri** [comment]
Solved.

**Comment by kimna4** [comment]
@AliBaheri 
I checked some .h5 files and it consisted of 200 sequential images.  
However, I'am not sure that all of these files have one sequential episode. 
I think that some .h5 files are likely to contain multiple episodes.
I want to know the answer to your question.

Thank you.

**Comment by ryanwang522** [comment]
Hi @kimna4 @AliBaheri 
I also have a similar question about how the data have been collected.
Should we extract all the images from these .h5 files and train our model with batched data?
