### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by AliBaheri** [carla-simulator/imitation-learning#51]
A quick question about the dataset:

Can you please clarify the target key # 24:
`High level command, int ( 2 Follow lane, 3 Left, 4 Right, 5 Straight)`???

**When I open a sample data, I see only a real value for this key. Should not be a vector of 5 real number based on its definition?**

    `Steer, float
    Gas, float
    Brake, float
    Hand Brake, boolean
    Reverse Gear, boolean
    Steer Noise, float
    Gas Noise, float
    Brake Noise, float
    Position X, float
    Position Y, float
    Speed, float
    Collision Other, float
    Collision Pedestrian, float
    Collision Car, float
    Opposite Lane Inter, float
    Sidewalk Intersect, float
    Acceleration X,float
    Acceleration Y, float
    Acceleration Z, float
    Platform time, float
    Game Time, float
    Orientation X, float
    Orientation Y, float
    Orientation Z, float
    High level command, int ( 2 Follow lane, 3 Left, 4 Right, 5 Straight)
    Noise, Boolean ( If the noise, perturbation, is activated, (Not Used) )
    Camera (Which camera was used)
    Angle (The yaw angle for this camera)`

**Comment by felipecode** [comment]
No, it is a real number.  And when
command == 2: 
follow lane,
command == 3
go left
command == 4
go right
command == 5
go straight
