### ISSUE TITLE
Question about dataset !!!

### ISSUE THREAD

**Issue by JunningHuang** [carla-simulator/imitation-learning#53]
I want to replicate the work of this paper, but I don't know how to load the data to rebuild the dynamics of other non-agent cars. Can you provide a detailed tutorial?
I have fought out that there is a default environment setting named "CORL2017", is this setting enough to rebuild the dynamics of other non-agent cars?

**Comment by Deepak3994** [comment]
Hi did you got any idea on this...As iam also facing the same problem in getting 28 control signals...

**Comment by JunningHuang** [comment]
> Hi did you got any idea on this...As iam also facing the same problem in getting 28 control signals...

It's impossible to restore the environment in 0.8.2. I recollect the expert data by the default autonomous driving control, you can try it. BTW, the newest 0.9.2 has some awesome features benefit the learning.
