### ISSUE TITLE
Training code?

### ISSUE THREAD

**Issue by AliBaheri** [carla-simulator/imitation-learning#55]
Is there any plan in near future to release the training code?

**Comment by felipecode** [comment]
I am working on it. The plan is for next month.

**Comment by markus-hinsche** [comment]
We released Tensorflow training code which tries to implement the paper: https://github.com/merantix/imitation-learning

**Comment by getaleks** [comment]
Any updates on this?

**Comment by Elahe96** [comment]
If anyone found a training code that has been published, please give the link.

**Comment by felipecode** [comment]
I released this long time ago a framework to train those type of networks.
https://github.com/felipecode/coiltraine
It is in pytorch.
