### ISSUE TITLE
Is this the result from CORL 2017 or CIL (ICRA 2018)?

### ISSUE THREAD

**Issue by onlytailei** [carla-simulator/imitation-learning#57]
For the CORL 2017 paper, it is trained by several different weather conditions.
For the CIL (ICRA 2018) paper, "The majority of training data was collected in sunny weather."

It seems that the dataset provided in this repo contains several different weather conditions. 
So the weight provided is trained by this dataset and represents the training result of CORL 2017 paper?

And if I split the dataset by myself, can I use the data under clean-noon weather to train the result of CIL (ICRA 2018)?

**Comment by felipecode** [comment]
No, the ICRA data is not available. You just have the CoRL paper data on this repo . I still have to organized and update this... but i am finishing my phd now...
