### ISSUE TITLE
Data collection question

### ISSUE THREAD

**Issue by TairuiWang** [carla-simulator/imitation-learning#7]
Hi, thanks for your great work!
Currently, I am going to collect more data for training. However, I have no idea how to achieve some of the measurement in your 'target list', such as '_control signal_'. I checked this [page](https://carla.readthedocs.io/en/latest/measurements/). I didn't find anything like '_control signal_' or  '_noise_'. How can I get those values?

**Comment by felipecode** [comment]
Hey @TairuiWang thanks for the attention and Sorry for the late answer,
It was my mistake on naming it. It should be called something like high level commands.
The control signal is obtained from the high level planner.
The planner plans a route towards to some target in the city and produces
a list of high level commands to lead the agent into getting to the target.

A common list of command would be :

[ STRAIGHT, STRAIGHT, TURN RIGHT, TURN LEFT]

Remember that this commands are not for micro managing the car. They 
just say what should the car do in the next intersection. Basically
the neural network adapts its policy conditioned on these high level commands.

The code to produce noise was not yet provided, but it basically adds 
perturbation to the steering.  Please, check the paper for details.

Cheers
