### ISSUE TITLE
python run_CIL.py error 

### ISSUE THREAD

**Issue by varunjammula** [carla-simulator/imitation-learning#80]
` File "<string>", line 32
    def single_image_random_dot_stereograms(depth_values, hidden_surface_removal=True, convergence_dots_size=8, dots_per_inch=72, eye_separation=, mu=, normalize=True, normalize_max=, normalize_min=, border_level=, number_colors=256, output_image_shape=[1024, 768, 1], output_data_window=[1022, 757], name=None):
                                                                                                                                                 ^
SyntaxError: invalid syntax
`

I am encountering this issue, when I try to run the code in python3.7, tensoflow-gpu 1.14, cuda-10, ubuntu 18. Any pointers?

**Comment by felipecode** [comment]
Try running the suggested versions please ! I haven’t updated it :(

**Comment by varunjammula** [comment]
It is an issue when CARLA is imported before tensorflow. Just need to be careful  about the import order.

**Comment by SHITIANYU-hue** [comment]
i also have this problem, how did you solve it? @varunjammula
